name: CI — NexaCloud API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@5
        with:
          python-version: "3.11"

      - name: insaller les indépendances
        uses: pip install -r ressources/requirements.txt

      - name: Lancer les tests
        uses: pytest ressources/ -v